### ISSUE TITLE
problems compiling ble_freertos_amdtps

### ISSUE THREAD

**Issue by penco193** [kerryeven/AndroidArtemisBleUartClient#1]
I tried to compile ble_freertos_amdtps code from your repository with AmbiqSuite-Rel2.1.0 for an Artemis Thing Plus board, and thye following error appears:
make: *** No rule to make target 'bin/port.o', needed by 'bin/ble_freertos_amdtps_asb.axf'.  Stop.
any help will be appreciated. thanks

**Comment by kerryeven** [comment]
If you are trying to compile from the GIT Bash shell then it is a Makefile problem...probably directory related.  In the readme, I speak about setting up the software and following the Spark Fun edge board tutorial related to Ambiq SDK, to copy files to the correct locations and get the toolchain setup.  Follow that tutorial and you should be able to make the Ambiq SDK server successfully with zero changes to the Makefile.   Next you need to add the Spark Fun bootloaders.  The easiest way would be to grab the Makefile from the repository GCC server directory and replace the one you just successfully used.  Then you can make bootload_asb to load it onto your board.   I would say you are definately having Makefile issues right now.   PS...you should be able to compile without a board in the sdk to make sure your toolchain is working.  Don't know where you are in your setup right now so hard to tell.  Let me know more...happy to help...works great 4 me..

I may update files in next few days with operational robot if I get around to it....

**Comment by penco193** [comment]
Hi again.

i used make bootload instead of make bootload_asb for flashing the code ...
can it be related to the reported problem?
thanks again
best regards
Félix

**Comment by kerryeven** [comment]
Step 1 would be to make with no arguments to see if it will compile.  Then add the bootload stuff.  Also, look carefully at the output from the make command and you should see a line number referenced.  That would be the line # in the Makefile that is having the problem....

**Comment by kerryeven** [comment]
Used SDK 2.2.0
1) from Git Bash Shell terminal window in Windows 10:
   cd down to gcc directory of amdtps example for apollo3 - my case:
    ~/Documents/AmbiqSuite-Rel2.2.0/boards/apollo3_evb/examples/ble_freertos_amdtps/gcc
2) type make and hit enter - should compile to point that last lines =
     Compiling gcc ../../../../../third_party/FreeRTOSv10.1.1/Source/timers.c
     Compiling gcc startup_gcc.c
     Linking gcc bin/ble_freertos_amdtps.axf
     Copying gcc bin/ble_freertos_amdtps.bin...

Success...Are you getting that far?
