### ISSUE TITLE
Integrate more than two bluetooth services

### ISSUE THREAD

**Issue by TaWeiYeh** [kerryeven/AndroidArtemisBleUartClient#3]
Hi Kerry, 

I wanted to implement new functions like reading a gyroscope sensor on my cell phone. And move the robot according to the orientation. Also, add new Bluetooth profiles in Artemis Nano, like reading off the battery level or the processor temperature. I think there are available services on Bluetooth. 
So is it possible to merge more than two services on Artemis Nano and the cell phone to recognize two different services as well? 

I'm studying how your app recognizes the Bluetooth profile "Amdtp" on Artemis Nano. It seems like the UUID is the key element. 

Thank you.

**Comment by kerryeven** [comment]
Yes, it is all about UUID's for ble.  Take a look in the Viper2_7 directory at the file 
svc_amdtp.c
SparkFun is working on implementing ble but they have been saying that for quite some time now.  Arduino ble has functions for creating / implementing services and, one day, the SF boards will hopefully support that type of easy development.  
My Android stuff came out of some old NrfConnect app source files that I updated to work with current Android Studio and changed their UUID's to the amdtp UUID's and it worked.  Adding new services is beyond me for now.  Please let me know if and how you succeed.  
Kerry
    On Thursday, May 14, 2020, 10:56:34 PM EDT, TaWeiYeh <notifications@github.com> wrote:  
 
 


Hi Kerry,

I wanted to implement new functions like reading a gyroscope sensor on my cell phone. And move the robot according to the orientation. Also, add new Bluetooth profiles in Artemis Nano, like reading off the battery level or the processor temperature. I think there are available services on Bluetooth.
So is it possible to merge more than two services on Artemis Nano and the cell phone to recognize two different services as well?

I'm studying how your app recognizes the Bluetooth profile "Amdtp" on Artemis Nano. It seems like the UUID is the key element.

Thank you.
