### ISSUE TITLE
Transfer more than two characters

### ISSUE THREAD

**Issue by TaWeiYeh** [kerryeven/AndroidArtemisBleUartClient#4]
Hi Kerry, 

I found out the android app can only transfer two characters at a time. Like "ok". However, any character larger than the two characters would be ignored. Like "what". Where could I modify the code to transfer more than two characters? Thank you. 

TaWei Yeh

**Comment by kerryeven** [comment]
amdtps_main.c line 536 
    if (len < 3) { //Just want to see robot command echo not ACK echo.          bleRxTxReceived(pValue,len);

    On Thursday, May 21, 2020, 08:40:22 PM EDT, TaWeiYeh <notifications@github.com> wrote:  
 
 


Hi Kerry,

I found out the android app can only transfer two characters at a time. Like "ok". However, any character larger than the two characters would be ignored. Like "what". Where could I modify the code to transfer more than two characters? Thank you.

TaWei Yeh

**Comment by TaWeiYeh** [comment]
Thank you. Problem solved. I'm trying to integrate the gyroscope detection in the App. I will upload my version for your reference.
